[18기 예병수] SignUpView 최종 수정 사항 반영 (Response Message 수정)
wecode-bootcamp-korea/18-1st-MarketHoly-backend pull request #2
Opened 2021-03-18 14:54 UTC by DevelopSoo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Response Message 수정

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- password 길이 상수로 수정
- response message 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-19 02:24 UTC, ulfrid requested changes
확인 부탁 드립니다~!

2021-03-19 02:24 UTC, devops-andrew commented on user/views.py
> +            password2     = data["password2"]
password는 하나만 받으면 됩니다. 일치 여부에 대한 검증은 Frontend 개발자가 하고 결정값을 받으면 됩니다.

2021-03-19 02:24 UTC, ulfrid commented on user/views.py
> +            user = User.objects.get(email=email)
```suggestion
           user =  User.objects.create(email=email, 
                                password=decoded_hashed_pw, 
                                name=name, 
                                phone_number=phone_number, 
                                date_of_birth=date_of_birth)
```

2021-03-19 02:24 UTC, ulfrid commented on user/views.py
> +            user = User.objects.get(email=email)
이렇게 하는게 두번 일하지 않겠죠?

2021-03-19 02:24 UTC, ulfrid commented on user/views.py
> +                                   detail_address=detail_address)
회원가입시에 무조건 주소를 입력하나요? 
그렇다면 만약 실패할 경우를 위해 transaction을 써보는게 좋을 것 같군요.
절대 실패하지 않을거라는 가정을 해서는 안되니까요~!
아래 공식문서자료를 첨부해드렸으니 참고해서 적용해보시고, 왜 해야 했는지 생각해보시고, 블로깅 해주시면 감사하겠습니다.
https://docs.djangoproject.com/en/3.1/topics/db/transactions/

2021-03-19 02:24 UTC, ulfrid commented on user/views.py
> +                return JsonResponse({"message": "주소를 입력해주세요."}, status=400)
Response 메세지가 너무도 친절한데 프론트의 요청사항인가요?

2021-03-19 02:39 UTC, ulfrid commented on user/views.py
> +                return JsonResponse({"message": "주소를 입력해주세요."}, status=400)
우리가 리스판스에서 메세지를 쓰는 이유는 이미 status 코드만으로도 충분하지만 위의 코드 중 같은 400을 놓고 본다면 결국 프론트 코드에서 3개의 400중 정확한 에러가 무엇인지 Validation하려면 한글로된 각각의 메세지를 비교해야하는데, 비효율 적입니다.
그래서 가이드에서 추천드리는  INVALID_KEYS,  USER_DOES_NOT_EXIST 등의 영문 대문자 및 언더스코어로 단어 구분을 하는 일종의 에러에대한 문자코드를 만들어서 관리하는 것입니다. 
우리는 프론트 코드와 통신을 하는것이지 실제로 고객과 대면하지 않습니다. 따라서 이러한 메세지 명명은 지양하는게 좋습니다. 꼭 메세지를 써야 한다면 위의 식별하는 코드를 따로 주고, 그에대한 메세지를 같이 제공해서 그 메세지를 프론트에서 사용하게 하는게 맞습니다.

2021-03-19 02:41 UTC, DevelopSoo commented on user/views.py
> +            password2     = data["password2"]
네 알겠습니다!

2021-03-19 02:42 UTC, DevelopSoo commented on user/views.py
> +            user = User.objects.get(email=email)
아하! 생성하면서 변수에 담을 수 있군요! 감사합니다!

2021-03-19 02:43 UTC, DevelopSoo commented on user/views.py
> +                                   detail_address=detail_address)
네 한 번 확인해보겠습니다.

2021-03-19 02:44 UTC, DevelopSoo commented on user/views.py
> +                return JsonResponse({"message": "주소를 입력해주세요."}, status=400)
아 그렇군요!! 최대한 자세하게 하려다보니 이렇게 작성했습니다! 수정하겠습니다~!

2021-03-19 06:16 UTC, ulfrid commented
질문에 답변을 이제 드립니다.
1. 보통은 이부분은 보내주는쪽의 잘못입니다. 물론 그렇게만 느슨하게 있고싶지 않다면 중복되는 키가 존재할 경우 에러를 리턴하면 될 뿐입니다.
2. 선택 사항은 저장해야 합니다. 개인정보의 동의사항이므로 법적으로 필요합니다~!

2021-03-19 07:09 UTC, DevelopSoo commented on user/views.py
> +                                   detail_address=detail_address)
@ulfrid 

transaction을 거는 이유가 모든 데이터가 들어가지 않았을 경우, 즉,  user 테이블에는 값이 들어가다가 address에 오류가 나면서 address테이블에는 값이 들어가지 않은 상황을 방지하기 위함인 것 같습니다.

그래서 장고 문서를 확인하여 transaction을 import한 후 데코레이터를 생성했습니다! 

잘 이해한건지 확신이 가지는 않는데 잘 이해한게 맞을까요???

2021-03-20 08:29 UTC, ulfrid requested changes
잘 하셨습니다.
1. 트랜잭션 동작시 각 리퀘스트에 대해 DB또한 트랜잭션이 수행되어 뷰코드의 결과에 따라 작동되는 부분을 설명한 것인데, 기본적으로 트루 입니다.
2. 에러코드는 임의의 협의 결정이 아니라 표준화된 약속입니다. 구글링 해보시면 워낙 잘 나옵니다. 본인의 상황에 맞게 사용하는게 맞습니다. 401이나 403은 인증정보, 인가정보 오류시의 문제이므로 회원가입 실패시에는 400 잘못된 요청이 맞습니다.
3. 컨플릭트 해결해주세요. 
4. 컨플릭트 해결시 지금 보시는 페이지에서 하시면 안됩니다!

2021-03-20 08:29 UTC, devops-andrew commented on user/views.py
> +                                   detail_address=detail_address)
네 잘 이해하셨습니다~!

2021-03-20 14:15 UTC, DevelopSoo commented
@ulfrid 

지훈님 머지 후 수정했습니다! 머지 커밋, status code 수정했는데, 잘 수행한거 맞을까요??

2021-03-21 02:04 UTC, ulfrid requested changes
최종 수정이 될 것 같습니다.

2021-03-21 02:04 UTC, ulfrid commented on user/views.py
> +                return JsonResponse({"message": "Conflict"}, status=409)
```suggestion
                return JsonResponse({"message": "EMAIL_ALREADY_EXIST"}, status=409)
```
혹은 EXIST_EMAIL 정도가 좋겠네요.

2021-03-21 02:04 UTC, ulfrid commented on user/views.py
> +            if len(password) < 10:
```suggestion
            if len(password) < MIN_PASSWORD_LENGTH:
```
비교조건에 있는 항목이 하드코딩되지 않도록 임포트 열 하단에  상수로 선언해서 적용해주세요.

2021-03-21 02:04 UTC, ulfrid commented on user/views.py
> +            signup_fail_response = JsonResponse({"message": "Bad Request"}, status=400)
이렇게 하나로 통일하게되면 문제해결에 어려움이 있을것 같네요.
그리고 아래의 not email, name, password, phone_number등의 리턴이 동일할거라면,
```
if not email or not password or not phone_number or not name:
과 같이 조건 문도 구간별로 설정하지 말고 합치는게 코드 라인 줄이는데 도움이 될 것 같습니다.

다만~ 에러 리스판스를 통일할 부분은 통일하되 너무 추상적으로 되서 에러파악이 힘들어 지면 안되므로, 적절히 통합해 주세요.

2021-03-21 05:22 UTC, DevelopSoo commented on user/views.py
> +                return JsonResponse({"message": "Conflict"}, status=409)
네 알겠습니다~!

2021-03-21 05:22 UTC, DevelopSoo commented on user/views.py
> +            if len(password) < 10:
네 알겠습니다~!

2021-03-21 05:22 UTC, DevelopSoo commented on user/views.py
> +            signup_fail_response = JsonResponse({"message": "Bad Request"}, status=400)
네 한 번 수정해보겠습니다~!

2021-03-21 08:54 UTC, ulfrid commented
LGTM👍

2021-03-21 08:54 UTC, merged