[MarketHoly backend 18기 예병수] 마켓컬리 '이 상품 어때요?' 관련 뷰 작성
wecode-bootcamp-korea/18-1st-MarketHoly-backend pull request #5
Opened 2021-03-21 14:15 UTC by DevelopSoo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 마켓컬리 '이 상품 어때요?' 관련 뷰(RecommendView) 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 마켓컬리 메인페이지에 있는 '이 상품 어때요?' 상품들을 표출하는 뷰 생성
- 전체 카테고리에서 랜덤한 카테고리를 뽑은 후 그 내부의 서브 카테고리 중 하나를 랜덤으로 추출, 서브 카테고리에서 상품 하나씩 랜덤으로 추출 후 모든 상품 표출
- 할인율이 존재하는 상품은 할인율을 보여주고, 아닐경우 원래 가격만 보여줌
- 컨벤션 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 마켓컬리에서 어떤 것을 기준으로 상품을 추출한 건지 감이 잡히지 않아서 일단 랜덤으로 뽑았습니다. 혹시 더 좋은 추출 기준이 있을까요??
- 5분간은 새로고침을 해도 같은 상품을 보여주고 싶은데, 구현하지 못했습니다. 스택오버플로우에서 random 모듈의 seed()함수를 통해 가능할 것 같다는 조언을 받았는데 쉽지 않네요...! 이것과 관련해서 조언을 받을 수 있을까요??

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-22 02:48 UTC, ulfrid requested changes
확인 바랍니다~!

2021-03-22 02:48 UTC, ulfrid commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
이제와서 드는 의문 점인데 할인율이 따로 테이블로 나눠진 이유가 있나요?

2021-03-22 02:48 UTC, ulfrid commented on product/views.py
> +                random_sub_category_list.append(random_sub_category)
```suggestion
            random_sub_category_list = []

            for category in random_categories:
                sub_categories      = category.subcategory_set.all()
                random_sub_category = random.choice(sub_categories)

                random_sub_category_list.append(random_sub_category)
```
리스트 컴프리헨션으로 변경해봅시다~!

2021-03-22 02:48 UTC, ulfrid commented on product/views.py
> +                random_product_list.append(random_product)
마찬가지입니다. 리스트 컴프리헨션을 찾아보고 코드를 간결화해봅시다.

2021-03-22 04:01 UTC, DevelopSoo commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
모델링을 할 당시에는 테이블을 나누는 기준에 대해서 정확하게 몰랐던 것 같습니다.
그리고 그때는 할인율의 경우 보통 10%, 5% 등 비슷한 할인율이 많다고 생각했었어요!

그래서 나눴었는데, 지금 생각하니 로직이 오히려 불편한 것 같네요!!

2021-03-22 04:23 UTC, DevelopSoo commented on product/views.py
> +                random_sub_category_list.append(random_sub_category)
네 알겠습니다~!

2021-03-22 04:23 UTC, DevelopSoo commented on product/views.py
> +                random_product_list.append(random_product)
넵~!

2021-03-22 16:10 UTC, ulfrid requested changes
주석은 메인 코드에 포함되면 안됩니다. 안쓰는건 다 제거해주시고, 최종 소스코드는 정말 필요한 주석외에는 제거해야 합니다. 정리해주세요. 
본인의 계획 pseudocode 는 제거해주세요.

2021-03-22 16:10 UTC, ulfrid commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
불편하다면 아직 늦지않았으니 수정해주세요.

2021-03-23 01:08 UTC, DevelopSoo commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
@ulfrid 
지금 MD추천, 베스트, 신상품 등 대부분 코드에서 이미 로직이 짜여진 상태에다가 임시 데이터도 꽤 입력한 상태라 오히려 수정하는데 시간을 너무 많이 쓸 것 같은데 크게 불편하지 않다면 놔둬도 괜찮을까요?
한 번 역참조하면 되는거라 크게 힘들진 않습니다.

2021-03-23 06:58 UTC, ulfrid requested changes
확인 바랍니다!

2021-03-23 06:58 UTC, ulfrid commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
그렇게 되면 아래의 로직과 같이 if/else 해야하는데 아에 디폴트로 상품에 박혀있으면 굳이 고려 안해도 될것 같습니다. 바꾸기 힘들다면 아래 로직을 그대로 사용하기보다, 리스트 컴프리헨션으로 정리하되 조건 연산자 처리로 결과값이 있다면 적용하고 아니면 None을 리턴하게 하는건 어떤가요?

https://jinmay.github.io/2020/05/28/python/python-list-comprehension-with-if-statement/
참고해주세요

2021-03-23 08:35 UTC, DevelopSoo commented on product/views.py
> +                    discount_rate = product.discountrate_set.all()[0].discount_rate
@ulfrid 네! 한번 적용해보겠습니다~! 감사합니다!!!

2021-03-23 10:18 UTC, ulfrid commented
더 개선 할 수 있을것 같은데, 이건 숙제로 드리겠습니다. 고생하셨습니다. LGTM 👍

2021-03-23 10:18 UTC, merged