[18기 김세형] Add: CategoryView 작성
wecode-bootcamp-korea/18-1st-MarketHoly-backend pull request #6
Opened 2021-03-22 02:05 UTC by sehyeongkim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카테고리 뷰 작성 , url 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- category 리스트를 get 메소드로 전달해줬습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Get method 에 대한 발생 가능한 에러를 생각하기가 어렵습니다. ㅠㅠ 제 머리론 db에 카테고리 내용들이 없을 때 에러가 발생할 것 같지만 그런다고 에러메세지를 띄우거나 하는 건 의미가 없는 것 같아 어떤 대응을 해야 하는지 의문입니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-22 02:10 UTC, sehyeongkim commented
프런트와 통신한 스크린샷

![image](https://user-images.githubusercontent.com/75714292/111931684-13e4fe00-8aff-11eb-89f9-4673e8b29483.png)

<img width="584" alt="스크린샷 2021-03-22 오전 11 00 05" src="https://user-images.githubusercontent.com/75714292/111931648-f9128980-8afe-11eb-8128-9099bc1aac61.png">

2021-03-22 02:50 UTC, ulfrid requested changes
확인 바랍니다~!

2021-03-22 02:50 UTC, ulfrid commented on product/views.py
> +            result.append(category_by_id)
리스트 컴프리헨션을 찾아보고 적용해서 코드를 간결하게 바꿔봅시다. 또 이렇게 사용하는것보다 리스트 컴프리헨션이 성능적으로도 더 좋은데 이유를 찾아보세요~!

2021-03-22 16:12 UTC, ulfrid requested changes
화이팅!

2021-03-22 16:12 UTC, ulfrid commented on product/views.py
> +
카테고리와 서브카테고리를 모두 뿌려주는 리스트 컴프리헨션으로 적용바랍니다. 아직 부족합니다.

2021-03-23 04:10 UTC, sehyeongkim commented
<img width="344" alt="스크린샷 2021-03-23 오후 1 07 45" src="https://user-images.githubusercontent.com/75714292/112091462-c4730080-8bd8-11eb-9e20-c8ef2df14e6d.png">

같은 카테고리 안에서 subcategory의 name을  list로 가져오고 싶었는데, 이중 for문을 각각 다르게 적용시키는 방법을 찾을 수 없어 제 선에서는 최선의 결과는 이렇게 subcategory 를 하나하나 뿌려주는 방법이었습니다. ㅠㅠ subcategory name을 list에 입력시키는 방법에 대한 힌트가 있을까요 ??

2021-03-23 10:25 UTC, ulfrid requested changes

2021-03-23 10:25 UTC, ulfrid commented on product/views.py
> +                   for sub_category in SubCategory.objects.filter(category=category)]
```suggestion
        result = [
            {
                'id': category.id,
                'category' : category.name,
                'subcategory': [
                    {
                        "sub_category_id     : sub_category.id,
                        "sub_category_name : sub_category.name
                    } for sub_category in SubCategory.objects.filter(category=category)
                ]
                } for category in categories ]
```
이렇게 하시면 될 것 같습니다. 근데 꼭 카테고리 뿌릴때 서브 카테고리도 같이 뿌려야 하나요?

2021-03-24 09:12 UTC, merged

2021-03-24 09:12 UTC, ulfrid commented
LGTM 👍