[18기 김세형] Add: DetailProductView 작성, url 추가
wecode-bootcamp-korea/18-1st-MarketHoly-backend pull request #7
Opened 2021-03-22 11:26 UTC by sehyeongkim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- DetailProductView 작성, url 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-22 11:29 UTC, sehyeongkim commented
![Uploading 스크린샷 2021-03-22 오후 8.09.09.png…]()

2021-03-22 11:30 UTC, sehyeongkim commented
<img width="825" alt="스크린샷 2021-03-22 오후 8 09 09" src="https://user-images.githubusercontent.com/75714292/111983436-7a910880-8b4d-11eb-90bf-3e126903e0ff.png">

2021-03-22 16:14 UTC, ulfrid requested changes
확인 바랍니다.

2021-03-22 16:14 UTC, ulfrid commented on product/views.py
> +            }
둘이 합쳐지면 코드라인이 많이 줄을것 같네요
```suggestion
            name            = product.name
            description     = product.description
            image_url       = product.image_url
            price           = product.price
            stock           = product.stock
            content         = product.content
            uploaded_at     = product.uploaded_at
            sales_unit      = product.sales_unit if product.sales_unit else []
            amount          = product.amount if product.amount else []
            origin          = product.origin if product.origin else []
            expiration_date = product.expiration_date if product.expiration_date else []
            storage_method  = product.storage_method.name if product.storage_method else []
            
            have_discount = DiscountRate.objects.filter(product=product).exists()
            if have_discount:
                discount      = DiscountRate.objects.get(product=product)
                discount_rate = discount.discount_rate
            else:
                discount_rate = []
            
            info = {
                'name': name,
                'description': description,
                'image_url': image_url,
                'price': price,
                'stock': stock,
                'content': content,
                'uploaded_at': uploaded_at,
                'sales_unit': sales_unit,
                'amount': amount,
                'origin': origin,
                'storage_method': storage_method,
                'expiration_date': expiration_date,
                'discount_rate': discount_rate,
            }
```

2021-03-23 01:39 UTC, sehyeongkim commented on product/views.py
> +            }
수정했습니당!

2021-03-23 04:42 UTC, sehyeongkim commented
- product의 id 가 존재하지 않을 때
<img width="1010" alt="스크린샷 2021-03-23 오후 1 33 29" src="https://user-images.githubusercontent.com/75714292/112093676-3d745700-8bdd-11eb-8aff-de3133d9ba0a.png">

- 성공
<img width="1019" alt="스크린샷 2021-03-23 오후 1 33 44" src="https://user-images.githubusercontent.com/75714292/112093724-50872700-8bdd-11eb-8121-e94788bbccb3.png">


- url에 id를 넣어주지 않았을 때
<img width="1207" alt="스크린샷 2021-03-23 오후 1 41 34" src="https://user-images.githubusercontent.com/75714292/112093839-7d3b3e80-8bdd-11eb-9de2-5a3560d6d54f.png">
MultiValueDictKeyError가 발생하는데 이 부분도 에러처리 해줘야하나요? 하려고 했더니 잡히지 않아서 고민입니다...!

2021-03-23 12:17 UTC, sehyeongkim commented
- product 상세 정보(이 전 커밋과 같음) 
<img width="840" alt="스크린샷 2021-03-23 오후 9 13 51" src="https://user-images.githubusercontent.com/75714292/112144885-03c34080-8c1d-11eb-8630-c22d3e1a095e.png">
- 새로 추가된 related_products 
<img width="881" alt="스크린샷 2021-03-23 오후 9 14 12" src="https://user-images.githubusercontent.com/75714292/112144974-205f7880-8c1d-11eb-97c9-3f0579c25190.png">

2021-03-24 02:27 UTC, ulfrid commented
말씀 드렸던 것 처럼 Produci_id를 url path parameter로 받도록 하는게 좋을 것 같습니다.

2021-03-24 09:26 UTC, merged

2021-03-24 09:26 UTC, ulfrid commented
LGTM 👍